version: "3.3"
services:
  sparkmaster:
    image: sparkmaster:v2
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_LOCAL_IP=sparkmaster
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: sparkworker:v2
    ports:
      - "8081-8083:8080"
    depends_on:
      - sparkmaster
    environment:
      - SPARK_MASTER=spark://sparkmaster:7077
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
